### ISSUE TITLE
No authentication method provided

### ISSUE THREAD

**Issue by avently** [kt97679/one-ssh#13]
Hello. Trying to start with your tool but having a problem related to auth. I compiled go version of the app and the result of running is: 
```bash
ossh -H "node-1" -l 'ubuntu' -c 'uptime'
No authentication method provided
```

At the same time python version:
```bash
ossh.py -H "node-1" -l 'ubuntu' -c 'uptime'
./one-ssh/py/ossh.py:214: DeprecationWarning: There is no current event loop
  self.loop = asyncio.get_event_loop()
./one-ssh/py/ossh.py:220: DeprecationWarning: There is no current event loop
  asyncio.ensure_future(self.start_dispatcher())
node-1  04:25:08 up 32 days,  3:05,  2 users,  load average: 0.13, 0.18, 0.18
```

So the go version is not working for me for some reason.

Contents of ~/.ssh/config is:

```bash
Host node-1
  HostName server_ip_here
  Port 22
  User ubuntu
  IdentityFile /absolute_path_to_file
  IdentitiesOnly yes
```

Of course SSH is working fine.

What can be a reason for such problem?

Also, I noticed that by default the app uses username of currently logged in user which is not comfortable because other servers often have different hostnames. So, let's say I have 10 servers. Some of them has a user named `ubuntu`, some of them has different username. Yhere is no way to use all the servers at once. But it should be a main purpose of the app, isn't it? Why the app is not choosing username based on `User` field form `.ssh/config'?

**Comment by kt97679** [comment]
Hi,

I'm sorry you have issues while using ossh. Please keep in mind that ossh logic is different from regular ssh. It doesn't use ~/.ssh/config and doesn't use by default any keys from the ~/.ssh. By default ossh relies on the ssh-agent since private keys are generally password protected so for convenient usage ssh-agent should be used to unlock key just once instead of typing password on every ossh invocation. You totally can use any private key you want by explicitly providing it via -k option.

Unfortunately at this point ossh doesn't support using different login names for different servers. I can try to implement this by providing username in the form login@host:port, that could be used with -H and -h options. Please let me know if you think this makes sense and will help you while using ossh.

Thanks,
Kirill.

**Comment by avently** [comment]
Ok, I understand. Probably you have other requirements for ossh.

I tried to specify -k option but got `lookup node-1: no such host`. I setup ssh agent, same situation (without -k, as it's unneeded in this case).

As you said, since it doesn't read ssh config, it doesn't know such host.

In readme you have written this:
```bash
ossh -H "db01 db02 web05 web06" -l root -c 'uptime'
```

So where is those labels has specified ip:port? By using ossh-inventory?

Anyway. I don't have thousands of servers, and maybe I don't need superfast execution of commands. I just installed parallel-ssh and it works out-of-the box with ssh config. I just specified host names and command. Which is good for my use-case.

If you want to make your app better, I would say that reading ssh config is important. Because different hosts has different ports, different IPs, usernames and even keys. If ssh agent solves some problems, it can't solve all of them. I don't know why you don't want to read ssh config, basic features can be parsed easily I think. For you it's probably one-two days of writing code. Or it's my imagination:)

I don't think adding support of specifying user@host:port will solve a problem. This method will not scale well. For those who has less than hundreds servers like me less performant tool would be enough. 

The issue can be closed if you don't plan to support ssh config (and it's completely fine, since this tool for other purpose).

**Comment by kt97679** [comment]
Here is a short example session:
```
# we start with SSH_AUTH_SOCK set by the ssh-agent
$ echo $SSH_AUTH_SOCK 
/tmp/ssh-m6UFwkBf9mBb/agent.1320
$ ossh -H 192.168.1.101 -n -c uptime
192.168.1.101  20:37:01 up 3 days, 13:11,  1 user,  load average: 0.39, 0.29, 0.27
# now let's unset SSH_AUTH_SOCK
$ unset SSH_AUTH_SOCK
$ ossh -H 192.168.1.101 -n -c uptime
No authentication method provided
# ossh failed since it couldn't find ssh-agent. Let's use private key explicitly. It is protected by the passphrase so we need to provide it
$ ossh -H 192.168.1.101 -n -c uptime -k ~/.ssh/id_rsa
SSH Passphrase: 
192.168.1.101  20:37:35 up 3 days, 13:12,  1 user,  load average: 0.22, 0.26, 0.26
$ 
```
"db01 db02 web05 web06" are just example names, they will be resolved via dns when you will run ossh.

Unfortunately parsing ssh_config is not trivial because of many reasons so I really don't want to add this functionality to ossh. It can be added though to the ossh-inventory helper. I'll see if I can create example for this use case. But I'll need to implement support for the user@host:port notation first.

Thank you very much for trying ossh and providing feedback. I'm truly sorry it didn't worked for you.

**Comment by avently** [comment]
@kt97679 nothing to worry about, thank you for your work

**Comment by kt97679** [comment]
Support for the user@host notation was added in https://github.com/kt97679/one-ssh/commit/f234650d0ad51d7b451f095a3d9750e6c47e0caa Unfortunately support of the ~/.ssh/config is much more complicated so I don't think I can add this in the foreseeable future. Being able to provide per host user via inventory helper looks like a reasonable compromise for me.

**Comment by avently** [comment]
@kt97679 thanks!
